### ISSUE TITLE
Build out complete product edit screen

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#17]
The current edit screen has just enough fields to make basic products but we'll need more before this is ready for MVP.

I think we should start with the following:

- [x] Image upload field for the main product image #20
- [x] Multiple price options (repeatable row similar to EDD admin) with name and amount for each #44
- [x] Product name
- [x] Product description with rich editor #45
- [x] Product excerpt #120 
- [x] Product files with upload (repeatable row like EDD core's admin) #44
- [x] Status
- [x] Product delete #11
- [x] #114 Fork `EDD_HTML_Elements` to `SellBird\Util\HTML`
- [x] #114 Create `SellBird\html()` helper and implement in the templates

Previously: https://github.com/SellBirdHQ/sellbird/issues/19

**Comment by DrewAPicture** [comment]
Image upload was added in #20.

**Comment by amdrew** [comment]
@DrewAPicture Let me know when image uploading is ready for testing, just tried but not seeing the same results as https://github.com/SellBirdHQ/theme/issues/20#issuecomment-326781444. Looks like there's a JS error, seeing it on the live site and local:

<img width="715" alt="screenshot 2017-09-05 21 10 38" src="https://user-images.githubusercontent.com/52581/30054015-c965d0d8-927e-11e7-8c77-1f69fe46e0f5.png">

**Comment by DrewAPicture** [comment]
@amdrew Please re-test with `SCRIPT_DEBUG` enabled. We don't have the kinks worked out currently with the minified global JS yet.

**Comment by amdrew** [comment]
👍 will do

**Comment by amdrew** [comment]
@DrewAPicture No luck with `SCRIPT_DEBUG` enabled. I don't see any JS errors but now I see:

<img width="1168" alt="screenshot 2017-09-06 16 03 19" src="https://user-images.githubusercontent.com/52581/30093973-07704ad6-931d-11e7-9ed1-e58fb2e9345f.png">

Also rolled back to before I made the last 2 commits but same issue as above.

**Comment by DrewAPicture** [comment]
Can you provide more details about what's working or not? If you're getting object dumps in the console then the Ajax is sending, it just isn't working.

**Comment by amdrew** [comment]
This is all I see when uploading an image:

<img width="872" alt="screenshot 2017-09-06 16 26 17" src="https://user-images.githubusercontent.com/52581/30094375-240b238e-9320-11e7-9baa-6e2bca00be2d.png">

And when I save the product it disappears:

<img width="841" alt="screenshot 2017-09-06 16 26 24" src="https://user-images.githubusercontent.com/52581/30094394-3891a698-9320-11e7-9cc9-3df300b2d15e.png">

**Comment by DrewAPicture** [comment]
What's your browser and operating system? The upload is triggered on the `change` event for the file input. So to test uploads it's not enough to just fill the input once and then refresh, you have to actually click the button and choose a file.

In terms of saving, the upload and subsequent preview updates a hidden input with the attachment ID. If the upload fails, no attachment ID.

**Comment by DrewAPicture** [comment]
Opened #44 for repeatable product price and file options, and #45 for the rich description editor.

**Comment by amdrew** [comment]
Firefox or Chrome, MacOS. Doesn't work on live site either.

**Comment by DrewAPicture** [comment]
The only thing I can think of is that you aren't testing as a member of a store. The front end dashboard currently displays for everyone regardless of whether they're the manager for a store. So try switching users to a store owner (wp-admin/users.php switch-to) and do it again.

**Comment by DrewAPicture** [comment]
I just tried it as my account on .com and it didn't work because it can't upload to a store that doesn't exist. Realistically we should stop showing the dashboard if you aren't a store owner.

**Comment by amdrew** [comment]
That's probably it. I'm just testing with what I know, which is my admin account

**Comment by amdrew** [comment]
@DrewAPicture Which user? I tried two and could not access the products page at all.

**Comment by pippinsplugins** [comment]
@amdrew do you have a store assigned to your user? Easy to get one by just going through registration if you don'yt.

**Comment by amdrew** [comment]
No, will do that! Not aware of how everything is working just yet

**Comment by DrewAPicture** [comment]
Rich text editor for the product description was added in #49 for #45.

**Comment by DrewAPicture** [comment]
FYI, repeatable pricing and file fields are now open for testing over on #44.

**Comment by DrewAPicture** [comment]
Added two checklist items for #114.

**Comment by DrewAPicture** [comment]
All product templates have now been refactored to leverage the `HTML` class where feasible, and I've also restructured them all to be more accessible (not using fieldsets where they aren't warranted, adding some aria attributes, introducing some structure via sections and h* tags, etc.).

I think all that's left here is adding an excerpt field. @pippinsplugins Do you want to do that via a textarea or another editor?

**Comment by pippinsplugins** [comment]
Textarea please.

**Comment by DrewAPicture** [comment]
Excerpt field added to product-edit and product-add + saving via #120.

That makes every item on the checklist complete. Closing :-)

**Comment by pippinsplugins** [comment]
:tada:!!!
