### ISSUE TITLE
Dashboard updates etc

### ISSUE THREAD

**Issue by amdrew** [SellBirdHQ/theme#184]
Issues directly related to this update:
* [x] #128 – Preview store link
* [x] #145 – Improve search filter UI
* [ ] #154 – Accessibility improvements – No testing needed
* [ ]  #148 – "Replace" image button shows intermittently when adding image to existing product - Ready for testing
* [ ] #174 – Billing page improvements - In progress. Some styling needed to close this one out.
* [ ] #65 – Beautify the Order Details template – In progress
* [x] #150 – Replace image button not working 
* [x] #146 – Style "Replace" button
* [ ] #133 – Dismiss home notices – In progress.
* [x] #130 – Mobile menu
* [x] #59 – Make HTML tables responsive 
* [ ] #26 – Use site logo or something as an "icon" when store owner is logged in to the dashboard – In progress
* [ ] #25 – Indicate logged-in user in the header (avatar/log out link) – A couple of items to address but can be tested in its current state
* [ ] #186 – Provide more meaningful screens when no data exists – In progress

## General testing notes

- Turn off the WP admin toolbar from your user profile when testing. I see us disabling it from the theme, since we will have our own profile menu.

**Comment by amdrew** [comment]
PR has been merged into master for testing

**Comment by pippinsplugins** [comment]
@amdrew could we make the `Settings` link sit at the bottom of the screen regardless of browser size? Right now it gets easily hidden.
<img width="1911" alt="screen shot 2018-04-05 at 8 59 25 am" src="https://user-images.githubusercontent.com/1034109/38370462-c294b12a-38af-11e8-821f-8ab4dfc63357.png">

**Comment by pippinsplugins** [comment]
@amdrew looks like the `Delete Product` screen got missed.
<img width="1733" alt="screen shot 2018-04-05 at 9 05 27 am" src="https://user-images.githubusercontent.com/1034109/38370787-891c3c8c-38b0-11e8-9902-3023f8226f76.png">

**Comment by amdrew** [comment]
@pippinsplugins See testing notes above, the admin toolbar will eventually be disabled, there's no need to show it to the logged in user. Once you disable the admin toolbar from your profile you'll see the Settings link just fine (and the header won't scroll awkwardly, since both header bars are fighting over positioning).

Yep, there are some screens that need to be redone after the PR, the product delete screen is on my list. The order page is another.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
The items I noted above were the only issues I noticed. Everything else looks excellent!

**Comment by amdrew** [comment]
Sweet!
