### ISSUE TITLE
Repeatable fields for product price and file options

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/theme#44]
Spawned from the checklist on #17:

**Multiple Price Options**:
* [x] #87 – Repeatable row similar to EDD for variable pricing (name and amount) (Edit/New Product)
* [x] #87 – Dynamically update a list of prices for use by the files repeatable (Edit/New Product)
* [x] #88 – Variable price handling on save for new products
* [x] #89 – Variable price handling on save for existing products

**Multiple File Options**:
* [x] #90 – Repeatable row similar to EDD for multiple files per product (Both)
* [x] #103 – Integrate variablle pricing fields into file rows (Both)
* [x] #94 – Improve handling of multiple files when saving existing products
* [x] #95 – Improve handling of multiple files when submitting new products
* [x] #91 – Ajax upload handling for each file + error/success display (preventing form submission) (Both)

**Other**:
* [x] #108 Remove "sellbird-" prefixes from most HTML attributes to improve readability

**Comment by DrewAPicture** [comment]
I've updated the first commend with a more complete checklist of what needs to happen for variable pricing and multiple file uploads to be possible. I've also created all of the individual issues and linked them back to this master checklist.

On its face, this appears like a fairly straightforward process of adapting EDD back-end code to work on the front-end, but it's much more than that. We have to handle the dynamic aspects already addressed in the back-end code (price and variable price options available for assignment to each file) but we don't have things like the media library here (and I don't recommend using it either).

Thus, Ajax upload for files, any visual feedback on success/failure, etc. have to be added. Lots of work all around.

**Comment by pippinsplugins** [comment]
Check list looks accurate to me.

**Comment by DrewAPicture** [comment]
Added two missed issues for improving how we handle saving multiple files on save for existing products and submit for new ones.

**Comment by DrewAPicture** [comment]
Base repeatable files for new and existing products is done, merged #90.

**Comment by DrewAPicture** [comment]
Ajax file uploads + basic output is done, merged #91.

**Comment by DrewAPicture** [comment]
Saving logic for one or more files for adding and editing products done, merged the PR for #95, which also fixed #94.

**Comment by pippinsplugins** [comment]
Just gave a quick test and is looking great1

**Comment by DrewAPicture** [comment]
Merged #87 which adds repeatable pricing fields and a checkbox to toggle pricing options. Note that in lieu of #88 and #89, _saving_ still won't always work.

**Comment by DrewAPicture** [comment]
#107 was merged to complete #87.

**Comment by DrewAPicture** [comment]
Added #108 to the checklist for removing the "sellbird-" prefixes from most HTML attributes to improve readability

**Comment by DrewAPicture** [comment]
The PR for #108 was merged.

**Comment by DrewAPicture** [comment]
The PR for #89 was merged.

Workflow changes:
* All pricing is now variable pricing
* Added logic for saving variable prices on save and displaying that saved info on load
* Added handling for saving the default price ID
* Added logic for removing prices from the file row drop-down(s) when price rows are removed
* Added some JS to strip query vars from the URL once the page is loaded (nice to have!)

**Comment by DrewAPicture** [comment]
The PR for #88 was merged, which also took care of #103.

@pippinsplugins The product page is now open for feedback and general testing. Note that the UI is obviously not in prime shape, @amdrew will take care of that soon enough. The basic things to test here are setting any of the fields (generally), as well as adding prices with and without names and with and without prices, see where stuff breaks.

The pricing is set up currently as "variable only" meaning that we have a "Price Name" field to contend with even when there's only one price. I've currently set it to just default to a label of "Price". There has been a _lot_ of JS written and tweaked for use on this page, so I imagine there may be errors, just report them, and we'll open new issues and add them to the checklist.

**Comment by pippinsplugins** [comment]
@DrewAPicture looking good!

Small issue: when a product has one price, the `default` box is checked. Clicking `Add New Price` unchecks it, leaving all of them unchecked.

**Comment by DrewAPicture** [comment]
@pippinsplugins I've opened a PR to handle minor fixes and stuff that comes up. The "default" being unchecked bug should be working on that PR: #113.

**Comment by DrewAPicture** [comment]
Closing this one as fixed. See #17 for what's left.
